#!/usr/bin/env bash
#displaying different fizzys

i=1
while [ $i -lt 101 ]
do
	if ((i%15==0))
	then
		echo "FizzBuzz"
	elif ((i%3==0))
	then
		echo "fizz"
	elif ((i%5==0))
	then
		echo "buzz"
	else
		echo "$i"
	fi
	((i++))
done
