#!/bin/enc bash
# shows time for 12 hrs and 59 mins

HOURS=0
while [ $HOURS -lt 13 ]
do
   echo "Hour: $HOURS"
   MINUTES=1
   while [ $MINUTES -lt 60 ]
   do
       echo $MINUTES
       Let MINUTES+=1
    done
    let HOURS+=1
done
